SNS_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sns/',include('sns.urls')),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('security/',include('security.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

security/urls.py
app_name='security'
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .views import ProfileUpdateView

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/security/login'),name='logout'),
    path('edit/',ProfileUpdateView.as_view(),name='profile_edit'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sns/urls.py
app_name='sns'
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('index/',views.index,name='index'),
    path('good/<int:good_id>',views.good,name='good'),
    path('goods_view/',views.goods_view,name='goods_view'),
    path('good_remove/<int:good_id>',views.good_remove,name='good_remove'),
    path('my_account/',views.my_account,name='my_account'),
    path('tweet/',views.tweet,name='tweet'),
    path('comment/<int:msg_id>',views.comment_view,name='comment'),
    path('comment_good/<int:comment_id>',views.comment_good,name='comment_good'),
    path('post_list/<int:user_id>',views.user_post_list,name='user_post_list'),
    path('post_delete/<int:msg_id>',views.delete_post,name='post_delete'),
]

security/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
# Create your models here.
class CustomUser(AbstractUser):
    avatar=models.ImageField(upload_to='avatars/',null=True,blank=True)

security/forms.py
# security/forms.py
from django import forms
from django.contrib.auth import get_user_model

# カスタムユーザーモデルを取得
User = get_user_model()

class CustomUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'avatar']
        labels={
            'first_name':'ユーザーネーム',
            'avatar':'プロフィール画像',
        }
        widgets={
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'avatar':forms.FileInput(attrs={'class':'form-control-file'}),
        }

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'first_name', 'email', 'avatar')

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = CustomUser
        fields = ('username', 'first_name', 'email', 'avatar')

security/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
User=get_user_model()

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('sns:index')
        else:
            return render(request,'security/login.html',{'error':'無効です。'})
    else:
        # GET リクエスト時の処理
        return render(request, 'security/login.html',{'error':''})

def signup(request):
    if request.method=='POST':
        email=request.POST.get('email')
        password=request.POST.get('password')
        first_name=request.POST.get('first_name')
        user=User.objects.create_user(username=email,email=email,password=password,first_name=first_name)
        user.save()
        return redirect('security:login')
    else:
        return render(request,'security/signup.html')

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from .forms import CustomUserForm
from .models import CustomUser

class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserForm  # 修正: formからform_classに変更
    login_url='/security/login/'
    template_name = 'security/profile_edit.html'
    success_url = reverse_lazy('sns:index')  # success_urlが正しく設定されているか確認
    
    def get_object(self, queryset=None):
        # ログイン中のユーザーインスタンスを返す
        return self.request.user
    
    def get_context_data(self, **kwargs):
        # 既存のコンテキストデータを取得する
        context = super().get_context_data(**kwargs)
        # コンテキストに新しい変数を追加する
        context['login_user'] = self.request.user
        return context

security/templates/security/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'security/login.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <title>login</title>
</head>

<body class="container">
    <h3 class="">{{error}}</h3>
    <div class="wrapper">
        <form method="post" class="form-signin">
            {% csrf_token %}
            <h3 class="form-signin-heading">サインイン</h3>
            <hr class="colorgraph"><br>
            <input type="text" class="form-control" name="username" id="username" placeholder="email" required>
            <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
            <button type="submit" class="btn btn-lg btn-primary btn-block">login</button>
            <br>
            <a href="{% url 'security:signup' %}" class="create_account">create account</a>
        </form>
    </div>
</body>
</html>

security/templates/security/profile_edit.html
<!DOCTYPE html>
{% extends 'SNS_project/layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'security/profile_edit.css' %}">
{% endblock css %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8"> <!-- 幅を広げたい場合はここの数値を調整 -->
            <div class="card">
                <div class="card-header">
                    プロフィール更新
                </div>
                <div class="card-body d-flex justify-content-center">
                    <form method="post" enctype="multipart/form-data" class="w-100">
                        {% csrf_token %}
                        <div class="form-group mb-3"> <!-- 項目間のスペースを増やす -->
                            <label for="id_first_name">ユーザーネーム</label>
                            {{ form.first_name }}
                        </div>
                        <div class="form-group mb-3"> <!-- 項目間のスペースを増やす -->
                            <label for="id_avatar">プロフィール画像</label>
                            {{ form.avatar }}
                        </div>
                        <button type="submit" class="btn btn-primary mx-auto d-block">プロフィール更新</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

security/templates/security/signup.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'security/login.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <title>signup</title>
</head>

<body>
    <div class="wrapper">
        <form method="post" class="form-signin">
            {% csrf_token %}
            <h3 class="form-signin-heading">Register your account</h3>
            <hr class="colorgraph"><br>
            <input type="email" name="email" id="email" placeholder="Mail Adress" class="form-control" required>
            <input type="password" name="password" id="password" placeholder="PassWord" class="form-control" required>
            <input type="text" name="first_name" id="first_name" placeholder="User Name" class="form-control" required>
            <button type="submit" class="btn btn-lg btn-primary btn-block">account creation</button>
            <a href="{% url 'security:login' %}" class="create_account">back to login</a>
        </form>
    </div>
</body>
</html>