SNS_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sns/',include('sns.urls')),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('security/',include('security.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

security/urls.py
app_name='security'
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .views import ProfileUpdateView

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/security/login'),name='logout'),
    path('edit/',ProfileUpdateView.as_view(),name='profile_edit'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sns/urls.py
app_name='sns'
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('index/',views.index,name='index'),
    path('good/<int:good_id>',views.good,name='good'),
    path('goods_view/',views.goods_view,name='goods_view'),
    path('good_remove/<int:good_id>',views.good_remove,name='good_remove'),
    path('my_account/',views.my_account,name='my_account'),
    path('tweet/',views.tweet,name='tweet'),
    path('comment/<int:msg_id>',views.comment_view,name='comment'),
    path('comment_good/<int:comment_id>',views.comment_good,name='comment_good'),
    path('post_list/<int:user_id>',views.user_post_list,name='user_post_list'),
    path('post_delete/<int:msg_id>',views.delete_post,name='post_delete'),
]

templates/SNS_project/layout.html
<!DOCTYPE html>
<html lang="ja">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'SNS_project/header.css' %}">
    {% block css %}{% endblock %}
    <title>{% block titile %}{% endblock %}</title>
</head>

<body>
    <header class="bg-primary fixed-top">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'sns:index' %}">SNSアプリ</a>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'sns:goods_view' %}">Good</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'sns:my_account' %}">マイアカウント</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'security:logout' %}">ログアウト</a>
                        </li>
                    </ul>
                    <div class="ms-auto">
                        <a class="nav-link" href="{% url 'security:profile_edit' %}">
                            {% if login_user.avatar %}
                            <img src="{{ login_user.avatar.url }}" alt="Profile" style="width: 50px; height: 50px;"
                                class="rounded-circle">
                            {% else %}
                            <img src="../../../media/avatars/avatar-not-set.png" alt="Default"
                                style="width: 50px; height: 50px;" class="rounded-circle">
                            {% endif %}
                            :{{ login_user.first_name }}
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>


    <main class="container">
        <div class="content1">{% block content %}{% endblock %}</div>
        <div class="fixed-bottom bg-white container">
            {% block form %}{% endblock form %}
        </div>
    </main>
    <footer>
        <a href="{% url 'sns:tweet' %}"><img src="../../media/pictures/plus.png" alt="plus_buttom"
                class="fixed-image"></a>
    </footer>
</body>

</html>