SNS_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sns/',include('sns.urls')),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('security/',include('security.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sns/urls.py
app_name='sns'
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('index/',views.index,name='index'),
    path('good/<int:good_id>',views.good,name='good'),
    path('goods_view/',views.goods_view,name='goods_view'),
    path('good_remove/<int:good_id>',views.good_remove,name='good_remove'),
    path('my_account/',views.my_account,name='my_account'),
    path('tweet/',views.tweet,name='tweet'),
    path('comment/<int:msg_id>',views.comment_view,name='comment'),
    path('comment_good/<int:comment_id>',views.comment_good,name='comment_good'),
    path('post_list/<int:user_id>',views.user_post_list,name='user_post_list'),
    path('post_delete/<int:msg_id>',views.delete_post,name='post_delete'),
]

sns/models.py
# Create your models here.
from django.db import models
from django.conf import settings
# Create your models here.

class Follow(models.Model):
    follower=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='following',on_delete=models.CASCADE)
    followed=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='followers',on_delete=models.CASCADE)
    pub_date=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together=('follower','followed')
    
    def __str__(self):
        return f'{self.follower} follow {self.followed}'

class Message(models.Model):
    owner=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='message_owner')
    content=models.TextField(max_length=1000)
    photo=models.ImageField(upload_to='photo/',null=True,blank=True)
    good_count=models.IntegerField(default=0)
    pub_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.content} by {self.owner}'
    
    class Meta:
        ordering=('-pub_date',)

class Good(models.Model):
    owner=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='good_owner')
    message=models.ForeignKey(Message,on_delete=models.CASCADE)
    pub_date=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.message} by{self.owner}'
    
    class Meta:
        ordering=('-pub_date',)

class Comment(models.Model):
    message=models.ForeignKey(Message,on_delete=models.CASCADE,related_name='comments')
    owner=models.ForeignKey(settings.AUTH_USER_MODEL,related_name='comment',on_delete=models.CASCADE)
    content=models.TextField(max_length=1000)
    pub_date=models.DateTimeField(auto_now_add=True)
    good_count=models.IntegerField(default=0)
    
    def __str__(self):
        return f'{self.message} commented by {self.owner}'
    
    class Meta:
        ordering=['-good_count','pub_date',]

class Comment_Good(models.Model):
    comment=models.ForeignKey(Comment,on_delete=models.CASCADE)
    owner=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='comment_good_owner')
    pub_date=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.message} by {self.owner}'

sns/forms.py
from django import forms
from .models import Message,Comment

class MessageForm(forms.ModelForm):
    class Meta:
        model=Message
        fields=['content','photo']
        widgets={
            'content':forms.Textarea(attrs={'class':'form-control'}),
            'photo':forms.FileInput(attrs={'class':'form-control-file'}),
        }
        labels={
            'content':'投稿内容',
            'photo':'',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content',]
        widgets={
            'content':forms.Textarea(attrs={
                'class':'form-control',
                'rows':2,
                'placeholder':'何を考えていますか？',
            }),
        }
        labels={
            'content':'コメント',
        }

sns/views.py
from django.shortcuts import render,redirect
from .models import Message,Good
from .forms import MessageForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.
@login_required(login_url='/security/login/')
def index(request):
    message=Message.objects.all()
    error=''
    if request.method=='POST':
        form=MessageForm(request.POST)
        if form.is_valid():
            # commit=Falseはsaveを保留する
            message2=form.save(commit=False)
            message2.owner=request.user
            message2.save()
            return redirect('sns:index')
        else:
            error='投稿に失敗しました。'
            return redirect('sns:index')
    else:
        form=MessageForm()
    params={
        'login_user':request.user,
        'message':message,
        'form':form,
        'error':error,
    }
    return render(request,'sns/index.html',params)

@login_required(login_url='/security/login')
def good(request,good_id):
    good_msg=Message.objects.get(id=good_id)
    is_good=Good.objects.filter(owner=request.user).filter(message=good_msg).count()
    is_good_instance=Good.objects.filter(owner=request.user).filter(message=good_msg)
    if is_good==1:
        is_good_instance.delete()
        good_msg.good_count-=1
        good_msg.save()
        return redirect('sns:index')
    else:
        good_msg.good_count+=1
        good_msg.save()
        good=Good()
        good.owner=request.user
        good.message=good_msg
        good.save()
        messages.success(request,'goodをしました')
        return redirect('sns:index')

@login_required(login_url='/security/login')
def goods_view(request):
    goods=Good.objects.filter(owner=request.user)
    params={
        'goods':goods,
        'login_user':request.user,
    }
    return render(request,'sns/goods.html',params)

@login_required(login_url='/security/login/')
def good_remove(request,good_id):
    good=Good.objects.get(id=good_id)
    good.delete()
    good.message.good_count-=1
    good.message.save()
    return redirect('sns:goods_view')


from security.models import CustomUser
from django.shortcuts import get_object_or_404
from .models import Follow

@login_required(login_url='security/login/')
def my_account(request):
    message=Message.objects.filter(owner=request.user)
    params={
        'message':message,
        'login_user':request.user,
    }
    return render(request,'sns/my_account.html',params)

@login_required(login_url='security/login/')
def tweet(request):
    if request.method=='POST':
        form=MessageForm(request.POST,request.FILES)
        if form.is_valid():
            message=form.save(commit=False)
            message.owner=request.user
            message.save()
            return redirect('sns:index')
        else:
            return redirect('sns:tweet')
    else:
        form=MessageForm()
    params={
        'login_user':request.user,
        'form':form,
    }
    return render(request,'sns/tweet.html',params)

from .forms import CommentForm
from .models import Comment

@login_required(login_url='security/login/')
def comment_view(request,msg_id):
    message=get_object_or_404(Message,id=msg_id)
    comments=Comment.objects.filter(message=message)
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.owner=request.user
            comment.message=message
            comment.save()
            params={
                'form':form,
                'm':message,
                'comments':comments,
                'login_user':request.user,
            }
            return redirect('sns:comment',msg_id=msg_id)
    else:
        form=CommentForm()
    params={
        'form':form,
        'm':message,
        'comments':comments,
        'login_user':request.user
    }
    return render(request,'sns/comment.html',params)

from .models import Comment_Good

@login_required(login_url='security/login')
def comment_good(request,comment_id):
    # いいねをしたコメントの抽出
    comment=get_object_or_404(Comment,id=comment_id)
    is_good=Comment_Good.objects.filter(owner=request.user).filter(comment=comment)
    is_good_count=is_good.count()
    if is_good_count==1:
        is_good.delete()
        comment.good_count-=1
        comment.save()
        return redirect ('sns:comment',msg_id=comment.message.id)
    else: 
        comment.good_count+=1
        comment.save()
        is_comment_good=Comment_Good()
        is_comment_good.owner=request.user
        is_comment_good.comment=comment
        is_comment_good.save()
        return redirect ('sns:comment',msg_id=comment.message.id)

@login_required(login_url='security/login')
def user_post_list(request,user_id):
    user=get_object_or_404(CustomUser,id=user_id)
    message=Message.objects.filter(owner=user)
    params={
        'message':message,
        'login_user':request.user,
    }
    return render(request,'sns/user_post_list.html',params)

def delete_post(request,msg_id):
    msg=get_object_or_404(Message,id=msg_id)
    if request.method=='POST' and msg.owner==request.user:
        msg.delete()
        return redirect('sns:my_account')
    else:
        return redirect('sns:index')

sns/templates/sns/comment.html
<!DOCTYPE html>

{% extends 'SNS_project/layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'sns/index.css' %}">
<link rel="stylesheet" href="{% static 'sns/comment_form.css' %}">
{% endblock css %}

{% block title %}
Comment
{% endblock title %}

{% block content %}
<table class="votion">
    <tr style="border: 2px solid black;">
        <td class="px-4 py-2">
            <div class="d-flex justify-content-between">
                <div>
                    {% if m.owner.avatar %}
                    <img src="{{ m.owner.avatar.url }}" alt="{{ m.owner.first_name }}"
                        style="width: 50px; height: 50px;" class="rounded-circle">
                    {% else %}
                    <img src="../../../media/avatars/avatar-not-set.png" alt="画像未設定" style="width: 50px; height: 50px;"
                        class="rounded-circle">
                    {% endif %}
                    <span>{{m.owner.first_name}}</span>
                </div>
                <span>{{m.pub_date|date:"Y/m/d"}}</span>
            </div>
            <p class="pt-3 content_position">
                {{m.content|linebreaksbr}}
            </p>
            <div class="container">
                {% if m.photo %}
                <img src="{{m.photo.url}}" alt="投稿画像エラー" class="photo">
                {% endif %}
            </div>
            <div class="d-flex justify-content-end my-2 left">
                <div>
                    <span><a href="{% url 'sns:good' m.id %}"><button>Good</button></a></span>
                    <span class="">{{m.good_count}}</span>
                </div>
            </div>
        </td>
    </tr>
    {% for m in comments %}
    <tr>
        <td class="px-4 py-2">
            <div class="d-flex justify-content-between">
                <div>
                    {% if m.owner.avatar %}
                    <img src="{{ m.owner.avatar.url }}" alt="{{ m.owner.first_name }}"
                        style="width: 50px; height: 50px;" class="rounded-circle">
                    {% else %}
                    <img src="../../../media/avatars/avatar-not-set.png" alt="画像未設定" style="width: 50px; height: 50px;"
                        class="rounded-circle">
                    {% endif %}
                    <span>{{m.owner.first_name}}</span>
                </div>
                <span>{{m.pub_date|date:"Y/m/d"}}</span>
            </div>
            <!-- 文章 -->
            <p class="pt-3 content_position">
                {{m.content|linebreaksbr}}
            </p>
            <div class="container">
                {% if m.photo %}
                <img src="{{m.photo.url}}" alt="投稿画像エラー" class="photo">
                {% endif %}
            </div>
            <div class="d-flex justify-content-end my-2 left">
                <div>
                    <span><a href="{% url 'sns:comment_good' m.id %}"><button>Good</button></a></span>
                    <span class="">{{m.good_count}}</span>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>
<!-- 幅を作る -->
<div class="h-10"></div>
{% endblock content %}


{% block form %}
    <form method="post" class="form-row w-50 d-flex justify-content-between">
        {% csrf_token %}
        <div class="w-80">
            {{form.as_p}}
        </div>
        <button type="submit" class="btn btn-primary w-15">投稿</button>
    </form>
{% endblock %}

sns/templates/sns/goods.html
<!DOCTYPE html>
{% extends 'SNS_project/layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'sns/index.css' %}">
{% endblock css %}

{% block title %}
Goods_view
{% endblock title %}

{% block content %}
<table class="votion">
    {% for good in goods %}
    <tr>
        <td class="px-4 py-2">
            <div class="d-flex justify-content-between">
                <div>
                    {% if good.message.owner.avatar %}
                    <img src="{{ good.message.owner.avatar.url }}" alt="{{ good.message.owner.first_name }}"
                        style="width: 50px; height: 50px;" class="rounded-circle">
                    {% else %}
                    <img src="../../../media/avatars/avatar-not-set.png" alt="画像未設定" style="width: 50px; height: 50px;"
                        class="rounded-circle">
                    {% endif %}
                    <span>{{good.message.owner.first_name}}</span>
                </div>
                <span>{{good.message.pub_date|date:"Y/m/d"}}</span>
            </div>
            <p class="pt-3 content_position">
                {{good.message.content|linebreaksbr}}
            </p>
            <div class="container">
                {% if good.message.photo %}
                <img src="{{good.message.photo.url}}" alt="投稿画像エラー" class="photo">
                {% endif %}
            </div>
            <div class="d-flex justify-content-between my-2 left">
                <div><a href="{% url 'sns:comment' good.message.id %}">コメント({{good.message.comments.count}})</a></div>
                <div>
                    <span><a href="{% url 'sns:good' good.message.id %}"><button>取り消し</button></a></span>
                    <span class="">{{good.message.good_count}}</span>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

sns/templates/sns/index.html
<!DOCTYPE html>

{% extends 'SNS_project/layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'sns/index.css' %}">
{% endblock css %}

{% block title %}
Index
{% endblock title %}


{% block content %}
<table class="votion">
    {% for m in message %}
    <tr>
        <td class="px-4 py-2">
            <div class="d-flex justify-content-between">
                <div>
                    <a href="{% url 'sns:user_post_list' m.owner.id %}" style="color: black; text-decoration: none;">
                        {% if m.owner.avatar %}
                        <img src="{{ m.owner.avatar.url }}" alt="{{ m.owner.first_name }}"
                            style="width: 50px; height: 50px;" class="rounded-circle">
                        {% else %}
                        <img src="../../../media/avatars/avatar-not-set.png" alt="画像未設定"
                            style="width: 50px; height: 50px;" class="rounded-circle">
                        {% endif %}
                        <span>{{m.owner.first_name}}</span>
                    </a>
                </div>
                <span>{{m.pub_date|date:"Y/m/d"}}</span>
            </div>
            <p class="pt-3 content_position">
                {{m.content|linebreaksbr}}
            </p>
            <div class="container">
                {% if m.photo %}
                <img src="{{m.photo.url}}" alt="投稿画像エラー" class="photo">
                {% endif %}
            </div>
            <div class="d-flex justify-content-between my-2 left">
                <div><a href="{% url 'sns:comment' m.id %}">コメント({{m.comments.count}})</a></div>
                <div>
                    <span><a href="{% url 'sns:good' m.id %}"><button>Good</button></a></span>
                    <span class="">{{m.good_count}}</span>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

sns/templates/sns/my_account.html
<!DOCTYPE html>

{% extends 'SNS_project/layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'sns/index.css' %}">
{% endblock css %}

{% block title %}
アカウント情報
{% endblock title %}

{% block content %}

<table class="votion">
    {% for m in message %}
    <tr>
        <td class="px-4 py-2">
            <div class="d-flex justify-content-between">
                <div>
                    {% if m.owner.avatar %}
                    <img src="{{ m.owner.avatar.url }}" alt="{{ m.owner.first_name }}"
                        style="width: 50px; height: 50px;" class="rounded-circle">
                    {% else %}
                    <img src="../../../media/avatars/avatar-not-set.png" alt="画像未設定" style="width: 50px; height: 50px;"
                        class="rounded-circle">
                    {% endif %}
                    <span>{{m.owner.first_name}}</span>
                </div>
                <div>
                    <span>{{m.pub_date|date:"Y/m/d"}}</span>
                    <div>
                        <form action="{% url 'sns:post_delete' m.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" onclick="return confirmDelete();">削除</button>
                        </form>
                        <script>
                            function confirmDelete() {
                                return confirm('本当にこの投稿を削除してもよろしいですか？');
                            }
                        </script>
                    </div>
                </div>
            </div>
            <p class="pt-3 content_position">
                {{m.content|linebreaksbr}}
            </p>
            <div class="container">
                {% if m.photo %}
                <img src="{{m.photo.url}}" alt="投稿画像エラー" class="photo">
                {% endif %}
            </div>
            <div class="d-flex justify-content-between my-2 left">
                <div><a href="{% url 'sns:comment' m.id %}">コメント({{m.comments.count}})</a></div>
                <div>
                    <span><a href="{% url 'sns:good' m.id %}"><button>Good</button></a></span>
                    <span class="">{{m.good_count}}</span>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

sns/templates/sns/tweet.html
<!DOCTYPE html>

{% extends 'SNS_project/layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'sns/tweet.css' %}">
{% endblock css %}

{% block title %}
投稿画面
{% endblock title %}

{% block content %}
<p>{{error}}</p>
<form method="post" class="pt-5" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="preformatted-text">
        {{form.as_p}}
    </div>
    <button type="submit">投稿</button>
</form>
{% endblock content %}

sns/templates/sns/user_post_list.html
<!DOCTYPE html>

{% extends 'SNS_project/layout.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'sns/index.css' %}">
{% endblock css %}

{% block title %}
アカウント情報
{% endblock title %}

{% block content %}

<table class="votion">
    {% for m in message %}
    <tr>
        <td class="px-4 py-2">
            <div class="d-flex justify-content-between">
                <div>
                    {% if m.owner.avatar %}
                    <img src="{{ m.owner.avatar.url }}" alt="{{ m.owner.first_name }}"
                        style="width: 50px; height: 50px;" class="rounded-circle">
                    {% else %}
                    <img src="../../../media/avatars/avatar-not-set.png" alt="画像未設定" style="width: 50px; height: 50px;"
                        class="rounded-circle">
                    {% endif %}
                    <span>{{m.owner.first_name}}</span>
                </div>
                <span>{{m.pub_date|date:"Y/m/d"}}</span>
            </div>
            <p class="pt-3 content_position">
                {{m.content|linebreaksbr}}
            </p>
            <div class="container">
                {% if m.photo %}
                <img src="{{m.photo.url}}" alt="投稿画像エラー" class="photo">
                {% endif %}
            </div>
            <div class="d-flex justify-content-between my-2 left">
                <div><a href="{% url 'sns:comment' m.id %}">コメント({{m.comments.count}})</a></div>
                <div>
                    <span><a href="{% url 'sns:good' m.id %}"><button>Good</button></a></span>
                    <span class="">{{m.good_count}}</span>
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}